export const PUZZLES = [
  {
    id: 'p1',
    title: 'Foundation',
    subtitle: 'The three languages everything starts with.',
    puzzle: '.A.. .A.C .A.C .BBC',
    exit: { side: 'bottom', position: 1 },
    skills: { A: 'Python', B: 'JavaScript', C: 'SQL' },
  },
  {
    id: 'p2',
    title: 'The Stack',
    subtitle: 'Production stack behind MDS and Rush Hour.',
    puzzle: '.A.... .A..C. .A..C. .BBB.. ...... ......',
    exit: { side: 'bottom', position: 1 },
    skills: { A: 'React', B: 'FastAPI', C: 'PostgreSQL' },
  },
  {
    // TODO: replace puzzle + skills with your real data
    id: 'p3',
    title: 'Full Toolkit',
    subtitle: 'Everyday dev essentials.',
    puzzle: '.A.... .A..C. .A..C. .BBB.. ...... ......',
    exit: { side: 'bottom', position: 1 },
    skills: {
      A: 'TypeScript',
      B: 'Tailwind',
      C: 'SQLAlchemy',
      D: 'Docker',
      E: 'Git',
      F: 'Linux',
    },
  },
  {
    // TODO: replace puzzle + skills with your real data
    id: 'p4',
    title: 'The Arsenal',
    subtitle: 'Everything in the toolkit.',
    puzzle: '.A.... .A..C. .A..C. .BBB.. ...... ......',
    exit: { side: 'bottom', position: 1 },
    skills: {
      A: 'You',
      B: 'Languages',
      C: 'Frontend',
      D: 'Backend',
      E: 'Databases',
      F: 'Cloud',
      G: 'AI/ML',
      H: 'Hardware',
      I: 'Tools',
      J: 'Security',
      K: 'CS Concepts',
      L: 'Learner',
    },
  },
  {
    id: 'p5',
    title: 'Foundation',
    subtitle: 'The three languages everything starts with.',
    puzzle: '.A.. .A.C .A.C .BBC',
    exit: { side: 'bottom', position: 1 },
    skills: { A: 'Python', B: 'JavaScript', C: 'SQL' },
  },
  {
    id: 'p6',
    title: 'The Stack',
    subtitle: 'Production stack behind MDS and Rush Hour.',
    puzzle: '.A.... .A..C. .A..C. .BBB.. ...... ......',
    exit: { side: 'bottom', position: 1 },
    skills: { A: 'React', B: 'FastAPI', C: 'PostgreSQL' },
  },
  {
    // TODO: replace puzzle + skills with your real data
    id: 'p7',
    title: 'Full Toolkit',
    subtitle: 'Everyday dev essentials.',
    puzzle: '.A.... .A..C. .A..C. .BBB.. ...... ......',
    exit: { side: 'bottom', position: 1 },
    skills: {
      A: 'TypeScript',
      B: 'Tailwind',
      C: 'SQLAlchemy',
      D: 'Docker',
      E: 'Git',
      F: 'Linux',
    },
  },
  {
    // TODO: replace puzzle + skills with your real data
    id: 'p8',
    title: 'The Arsenal',
    subtitle: 'Everything in the toolkit.',
    puzzle: '.A.... .A..C. .A..C. .BBB.. ...... ......',
    exit: { side: 'bottom', position: 1 },
    skills: {
      A: 'You',
      B: 'Languages',
      C: 'Frontend',
      D: 'Backend',
      E: 'Databases',
      F: 'Cloud',
      G: 'AI/ML',
      H: 'Hardware',
      I: 'Tools',
      J: 'Security',
      K: 'CS Concepts',
      L: 'Learner',
    },
  },
];

export const STORAGE_KEY = 'rush-hour-skills-v1';